CREATE TABLE APP_SUMMARY (EPOCH BIGINT, SEQ SMALLINT, USER CHAR(16), JOBNAME CHAR(255), QUEUE CHAR(32), START BIGINT , FINISH BIGINT, CPUHOUR BIGINT);
CREATE TABLE TASK_DETAIL (EPOCH BIGINT, SEQ SMALLINT, TYPE CHAR(1), TASKID BIGINT, ATTEMPTID SMALLINT, START BIGINT, FINISH BIGINT);
CREATE TABLE EXECUTOR_DETAIL (EPOCH BIGINT, SEQ SMALLINT, ID SMALLINT, START BIGINT);
CREATE TABLE  LAST_PROCESSED (ID INT, LAST BIGINT);
INSERT INTO LAST_PROCESSED (ID, LAST) VALUES (1,0);
